apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: alfio
  name: alfio
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: alfio
  type: LoadBalancer
status:
  loadBalancer: {}
