version: "3.0"
services:
  alfio:
    image: alfio/alf.io
    environment:
      POSTGRES_PORT_5432_TCP_PORT: 5432
      POSTGRES_PORT_5432_TCP_ADDR: db
      POSTGRES_ENV_POSTGRES_DB: alfio
      POSTGRES_ENV_POSTGRES_USERNAME: alfio
      POSTGRES_ENV_POSTGRES_PASSWORD: alfio
      SPRING_PROFILES_ACTIVE: dev,jdbc-session
    ports:
      - "8080:8080"
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: alfio
      POSTGRES_USER: alfio
      POSTGRES_PASSWORD: alfio
    ports:
       - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
volumes:
  data-volume:
